version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (only weekdays)
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope

  # Enable version updates for github-actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Check for updates to GitHub Actions monthly
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
