name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4

      - name: 🔍 Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: ⚙️ Setup Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: ➕ Install dependencies
        run: npm ci

      - name: ⚒️ Build project
        run: npx lerna run build

      - name: 📝 Lint codebase
        run: npx lerna run lint

      - name: 🧪️ Execute unit tests with coverage
        run: npx lerna run test:coverage
