name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v5

      - name: 🔍 Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: ⚙️ Setup Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: ➕ Install dependencies
        run: npm ci --include=optional

      - name: ⚒️ Build project
        run: npm run build --if-present --ws

      - name: 📝 Lint codebase
        run: npm run lint --if-present --ws

      - name: 🧪️ Execute unit tests with coverage
        run: npm run test:coverage --if-present --ws
